### ISSUE TITLE
request: bf3

### ISSUE THREAD

**Issue by BETLOG** [Unity-Technologies/qstat#118]
Please add support for Battlefield 3

...and any of the other battlefield series that use similar query protocols

**Comment by stevenh** [comment]
You should be able to use `bfbc2` for the bf3 and later.

**Comment by BETLOG** [comment]
My bad. My script was assuming a port offset.
Can you comment on server rcon query ports for the battlefield series?
ie: gametracker.com shows the server IP:port, for bfbc2 this port requires an offset of +29321 (eg:19567+29321=48888) for qstat to work, but apparently does not for bf3. (ie: the port listed on gametracker is the correct query port for qstat)
What's with that? Is that a quakestat oversight? or EA/DICE being weird?
